### ISSUE TITLE
diffSplice returns an error for a parameter that is already set

### ISSUE THREAD

**Issue by mksamur** [comprna/SUPPA#32]
I got following error message when I tried to use diffSplice function for isoforms. I tried the function with -nan , --nan-threshold and without both but still getting the same error message

python3 ../SUPPA-2.3/suppa.py diffSplice -m classical -p mmIsoform_isoform.psi normalIsoform_isoform.psi -e mmTPM.txt normalTPM.txt -i ../GencodeV24/gencode.v24.ioi -o IsoformDiffSplice -nan 0.01 -th 0.5 -mo DEBUG
Calculating differential analysis between conditions: mmIsoform_isoform and normalIsoform_isoform
/usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:4911: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
ERROR:__main__:Unknown error: (<class 'TypeError'>, TypeError("calculate_delta_psi() missing 1 required positional argument: 'nan_th'",), <traceback object at 0x16ff15888>)

**Comment by EduEyras** [comment]
Hi,

This is strange as it is complainig for a z-score calculation, but you are using the classical test, which uses a non-param test. 
Maybe some options are not checked properly? 

E

Dr. Eyras
ICREA Research Professor
Universitat Pompeu Fabra
Barcelona
Spain

**Comment by mksamur** [comment]
Hi,
It seems like the error actually comes from nan_th argument. I hard coded all nan_th s as 0.0 in diff_tools and it worked. Seems like it is not transferring the arguments as it suppose to do.

**Comment by EduEyras** [comment]
I found the bug. I'm writing the fix right now and I will commit it today.
Cheers
JC

**Comment by JLTrincado** [comment]
Fixed issue. 

Thanks mksamur for the time

**Comment by shum-sky** [comment]
Hi, I was trying to do the same thing mksamur did, and got the same error. Upon checking the diff_tools.py file I found that the committed changes were not present, so perhaps the commit did not go to the master branch. However, when I fixed the code as was shown in the commit, nothing changed, the same error is still passed. My code:

`python ~/SUPPA-2.3/suppa.py diffSplice -m classical -i splicing.events.ioe -p WT_ND.psi KO_ND.psi -e WT_ND.tpm KO_ND.tpm -o KO_NDvsWT_ND4 --save_tpm_events -nan 0.01 -th 0.5`

**Comment by jaganmskcc** [comment]
I do have the same issue when I use choose classical method, I replaced the diff_tools.py file from repository, which has nan_th argument definition at line 532. My previous diff_tools.py file which was from conda installation, doesn't mention about this argument at line 532. But even after replacing the diff_tools.py file from the repository, the same error is still passed.
